import { Date } from 'mongoose';
import { CommentResponseDto } from './comment-response.dto';
import { ExpertVerificationDto } from './expert-verification.dto';

export class PatternResponseDto {
  id: string;
  patternType: string;
  websiteId: string;
  isAutoGenerated: boolean;
  createdByExpertId: string;
  expertName: string;
  description: string;
  detectedUrl: string;
  patternImageUrls: string[];
  createdAt: Date;
  patternPhase: string;
  isPatternExists: boolean;
  comments: CommentResponseDto[];
  expertVerifications: ExpertVerificationDto[];
}
